version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://192.168.130.30:10443
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=$$argon2id$$v=19$$m=65540,t=3,p=4$$N2xoMk5YV2FPdWpUbFB4eUNZUUd4QnZ2amJacnhOM3FNRmJJb2dKRGk1UT0$$wG9oaVmMWrTsm75/16IYOsCED6eVaTOSk/7iRZq8xpI
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 10443:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$$argon2id$$v=19$$m=65540,t=3,p=4$$WnZhQW8rRFBNK1FKVWd4V3RDaGxSRlNodjhTUFU3UTZlaC9NU29IRUoyST0$$M1OhIqoMgwkAC9PJgPNXEs4dtOMjM+eD6K5HJC+GogM
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=$$argon2id$$v=19$$m=65540,t=3,p=4$$N2xoMk5YV2FPdWpUbFB4eUNZUUd4QnZ2amJacnhOM3FNRmJJb2dKRGk1UT0$$wG9oaVmMWrTsm75/16IYOsCED6eVaTOSk/7iRZq8xpI
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
